### ISSUE TITLE
Error "Validation failed for tx-steps"

### ISSUE THREAD

**Issue by omaishar** [instantdb/instant#112]
I was hoping someone can help with the following error: `Validation failed for tx-steps`.

Started playing with InstantDB using this simple and naive code, but it keeps failing.

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/0dbc0395-5412-4ffd-ad88-4f2bbea01052">

The code:
```
  const db = init<InstantSchema>({ appId: INSTANTDB_APP_ID });

  db.subscribeQuery({ collaborators: {} }, (resp) => {
    console.log("Reading data...")
    if (resp.error) {
      console.error(resp.error.message);
      return;
    }

    if (resp.data) {
      console.log(`Found ${resp.data?.collaborators?.length} collaborators...`);
    }
  });

  db.transact(tx.collaborators[collaboratorId].update({
    name: collaboratorName,
  }));
```

**Comment by dwwoelfel** [comment]
@omaishar It looks like it is unhappy that your collaboratorId is not a uuid. We could use a better error there.
