### ISSUE TITLE
I will write a Datomic-based storage backend

### ISSUE THREAD

**Issue by he-la** [instantdb/instant#141]
I am very likely going to fork this to implement a storage backend that uses Datomic instead of Postgres, and wanted to get some feedback on whether that would be interesting to the instantdb community at large.

I am doing this because I have somewhat unique requirements, so I don't expect many people to be in this same boat with me. But the internet can be larger than we think :)

Broadly, there is two paths that I can see myself taking:

---

**Option 1: Upstreaming Changes**

I can upstream my changes, effectively refactoring instantdb to support multiple storage backends. This is probably going to be some additional effort for me, but I am open to it if there is interest from instantdb or the community on having support for other storage backends besides postgres (for example, we could over time build up an `instant-contrib` repo with community implementations for other backends, such as DynamoDB ec).

Abstracting out the storage backend is probably going to introduce a modest amount of additional complexity and maintenance burden to the codebase, though I expect this to be fairly limited since the underlying triplestore model is simple.

**Option 2: Fork**

If there is no interest in abstracting out the storage backend (which I would totally understand), then I will probably just fork the repo and let the Datomic version become its own, in many ways worse and less maintained thing.

---

I expect to start working on this only in a few weeks, so there is plenty of time to gather opinions.

**Comment by stopachka** [comment]
Hey Henrik! 

I think an abstract storage backend is a good idea, but it's not something we want to focus on yet. Right now we want to focus on 'core Instant': Making the client SDK, query system, and sync engine fast and expressive. Would you be interested in contributing to these core features? If so, send me an email: stopa@instantdb.com
