### ISSUE TITLE
Use Instant via <script> tag

### ISSUE THREAD

**Issue by tomyo** [instantdb/instant#20]
https://www.instantdb.com/docs/start-vanilla

How can I try/run instantDB for my static site that has no npm dependencies?

Thanks!

**Comment by markyfyi** [comment]
Merged as of `0.12.18` https://github.com/instantdb/instant/pull/100

UMD  build: https://unpkg.com/@instantdb/core@0.12.18/dist/standalone/index.umd.js
ESM build: https://unpkg.com/@instantdb/core@0.12.18/dist/standalone/index.mjs
