### ISSUE TITLE
more `where` operators 

### ISSUE THREAD

**Issue by holic** [instantdb/instant#31]
Is there a technical/design reason common SQL operators like less than, greater than, not in, not equal to aren't available?

**Comment by Bshal** [comment]
Instadb likely omits the mentioned operators to maintain simplicity and ensure ease of use, which aligns with its design philosophy. This choice might limit certain advanced queries, but it keeps the language more accessible. If these operators are needed, it could be worth suggesting them as feature requests to the developers.

**Comment by dwwoelfel** [comment]
Instant does have support for `in` ([doc](https://www.instantdb.com/docs/instaql#in)). It looks like:

```js
const query = {
  todos: {
    $: {
      where: {
        title: { in: ['Code a bunch', 'Review PRs'] },
      },
    },
  },
};

```

We will support more comparison operators. The reason they're not supported now is that we still have some work to do building support for the indexes we'll need to make comparisons efficient. But it's coming!

**Comment by dwwoelfel** [comment]
less than, greater than, and not are all supported on any typed and indexed attribute.

It looks like:

```js
const query = {
  todos: {
    $: {
      where: {
        timeEstimateHours: { $gt: 24 },
      },
    },
  },
};
```

 More info in the docs https://www.instantdb.com/docs/instaql#comparison-operators
