### ISSUE TITLE
Bug: can't create items with `id` inside the object

### ISSUE THREAD

**Issue by skoshx** [instantdb/instant#332]
So basically, trying to create items in the "database" that contain `id` inside the object itself fails silently.

Repro code:

```typescript
const idD = typeid("pom").toString() // this generates a Type ID "pom_..."
const px = await db.transact([tx.pomodoros[id()].update({
            id: idD,
            type: 'work',
            status: 'paused'
} satisfies NewPomodoroType)]);
console.log("transaction result : ")
console.log(px)
```

Transaction result says:

`{status: 'synced', clientId: '07380714-....-....-...-.....'}`

But when checking the dashboard, the schema is created, but there are 0 rows.

Uncommenting line `id: idD` fixes the problem.

**Comment by nezaj** [comment]
We deployed a fix on the backend for this so should no longer be an issue!
