### ISSUE TITLE
`id` from `@instantdb/admin` doesn't have a type unless I import `@types/uuid`

### ISSUE THREAD

**Issue by ayoung19** [instantdb/instant#36]
This is just a minor problem and I'm not sure how it can be fixed. Maybe just adding a note in the docs when it instructs you to install `@instantdb/admin` or `@instantdb/react`?

**Comment by dwwoelfel** [comment]
Thanks for reporting!

This should be fixed in `0.12.9`. Please reopen the issue if you're still hitting the issue.
