### ISSUE TITLE
`lookup` issue

### ISSUE THREAD

**Issue by ayoung19** [instantdb/instant#42]
I'm getting this error:
```
Unhandled Runtime Error
Error: playerId is not a unique attribute.

Source
src/components/App.tsx (43:8) @ transact

  41 |
  42 |   useEffect(() => {
> 43 |     db.transact([
     |        ^
  44 |       tx.movements[lookup("playerId", user.id)].update({
  45 |         x: movement.x,
  46 |         y: movement.y,
```

trying to do this write operation ([link](https://github.com/ayoung19/instant-ctf/blob/e730c2666dbff6606272aa52cf71fa652ff52ee8/src/components/App.tsx#L43-L48)):
```
    db.transact([
      tx.movements[lookup("playerId", user.id)].update({
        x: movement.x,
        y: movement.y,
      }),
    ]);
```

with the following schema ([link](https://github.com/ayoung19/instant-ctf/blob/e730c2666dbff6606272aa52cf71fa652ff52ee8/instant.schema.ts)):
```
import { i } from "@instantdb/core";

const graph = i.graph(
  "c7a8aae8-5bfc-43e7-9be1-6f439475a114",
  {
    movements: i.entity({
      playerId: i.string().unique().indexed(),
      x: i.number(),
      y: i.number(),
    }),
  },
  {}
);

export default graph;
```

What am I doing wrong here? I'm simply trying to update the movements entity by its unique `playerId` attribute. As a sanity check, here are the attribute settings in the dashboard: 

<img width="614" alt="image" src="https://github.com/user-attachments/assets/9d1f3c61-3ca8-42d0-88a6-8eed1d89c9f2">

**Comment by dwwoelfel** [comment]
The underlying issue is that the `db.transact` happens before the client has fetched its attributes and so it doesn't know that it's a unique attribute.

Working on a fix.

**Comment by dwwoelfel** [comment]
This should be fixed in 0.12.9. Please reopen and ping me if you're still having issues.

**Comment by Zeb88** [comment]
> This should be fixed in 0.12.9. Please reopen and ping me if you're still having issues.

This issue seems to persist in  "@instantdb/react": "^0.12.14".  Here's my query - 

```
instantDb.transact([
    tx.readings[lookup('positionId', reading.positionId)].update(reading).link({ jobs: reading.jobId }),
 ]);
```

**Comment by dwwoelfel** [comment]
@Zeb88 what's the error that you're seeing here?

**Comment by dwwoelfel** [comment]
Should be fixed by https://github.com/instantdb/instant/pull/161 in version 12.0.27. Please @ me if you're still seeing the issue after upgrading.

**Comment by xavierchow** [comment]
I'm still experiencing the `is not a unique attribute` issue on @instantdb/react@v.014.12,
it does seem to be a timing issue, if the `lookup` gets triggered too early it throws such error.

**Comment by haf** [comment]
I'm also getting to an error like this, but I'm not using `lookup` or the ilk. https://discord.com/channels/1031957483243188235/1148284450992574535/1323109912615714980
