### ISSUE TITLE
It is a bit weird that `InstantEntity` requires the db object after initiate and not the abstract schema

### ISSUE THREAD

**Issue by uriva** [instantdb/instant#470]
If  your project has a backend, and they are in the same repo, you'd want to depend on the same schema file.

This means it would be preferrable to have `InstantEntity<schema, ...>` rather than the existing `InstantEntity<typeof db, ...>`, as this means you can have the same file with all your types shared between the backend and frontend.

**Comment by stopachka** [comment]
This is a great point @uriva ! 

In `v0.15.2` onwards, we've deprecated `InstantEntity`, in favor of `InstaQLEntity`. This lets you infer directly from schema, rather than `db`. i.e:

```typescript
// Before
const db = init_experimental({ ...config, schema }); 
type DB = typeof db; 
type MyEntity = InstantEntity<DB, "myEntityName">;
 
// After 
type Schema = typeof schema; 
type MyEntity = InstaQLEntity<Schema, "myEntityName">;
```

**Comment by uriva** [comment]
@stopachka '"@instantdb/admin"' has no exported member named 'InstaQLEntity'. Did you mean 'InstantEntity'?ts(2724)
