### ISSUE TITLE
Setting an object key to undefined doesn't work locally

### ISSUE THREAD

**Issue by jmandel** [instantdb/instant#54]
Here's an example of code that works _only when it's able to round-trip through the instantdb backend_. In other words,  my React component updates appropriately when the network is online, but fails to work locally when network is offline:

```
    await db.transact([
      tx.room[room.id].merge({
        players: {
          [playerName]: undefined
        }
      })
    ]);

```

I can work around this with the following (which works offline as well as online):

```
    await db.transact([
      tx.room[room.id].update({
        ...room,
        players: Object.fromEntries(
          Object.entries(room.players || {}).filter(([name]) => name !== playerName)
        ),
      })
    ]);

```

... but this shouldn't be required, according to https://www.instantdb.com/docs/instaml#:~:text=Sometimes%20you%20may%20want%20to%20remove%20keys, and the inconsistent behavior (offline vs online) is hard to reason about.

**Comment by nezaj** [comment]
Thanks for reporting this! We're going to look into this soon!

**Comment by jmandel** [comment]
Thanks for the response and the quick fix! You all are doing great work.
