### ISSUE TITLE
server side typing issue

### ISSUE THREAD

**Issue by uriva** [instantdb/instant#649]
I wrote this:
`const { users } = await db.query({ users: { $: { where: { id } } } });`

and then I don't see type information for `users[0]`

**Comment by stopachka** [comment]
Hey @uriva, I wrote up a rough repro: 

```javascript
import { init, i } from "@instantdb/admin";

const dbWithoutSchema = init({
  appId: "....",
  adminToken: "...",
});

const { users: usersWithoutSchema } = await dbWithoutSchema.query({
  users: { $: { where: { id: "id" } } },
});

const schema = i.schema({
  entities: { users: i.entity({ email: i.string() }) },
});

const dbWithSchema = init({
  appId: "....",
  adminToken: "...",
  schema,
});

const { users: usersWithSchema } = await dbWithSchema.query({
  users: { $: { where: { id: "id" } } },
});

usersWithoutSchema;

usersWithSchema;
```

When I hover over `usersWithoutSchema`, I see: 

<img width="343" alt="CleanShot 2024-12-20 at 11 35 07@2x" src="https://github.com/user-attachments/assets/23cdd90e-31f6-49d3-81db-07a78b551c7b" />

When I hover over `usersWithSchema`, I see: 

<img width="369" alt="CleanShot 2024-12-20 at 11 35 22@2x" src="https://github.com/user-attachments/assets/f228ba3f-a367-4177-bdf6-55a591c07a50" />


--- 

Do you mind sharing a repro I could look into?

I made a Replit of the above if it makes it easier, though I realize it requires a sign up. (Will look into a simpler repro tool for admin later)

**Comment by uriva** [comment]
I think it's an IDE thing
comes and goes
closing, sorry for the trouble

**Comment by uriva** [comment]
no sorry my mistake, it's still there

**Comment by uriva** [comment]
@stopachka the only difference between my setup and yours is that i define the schema with the react lib, and init using the admin lib

the typing i get is `InstaQLResponse<Schema, Q>`

**Comment by uriva** [comment]
I tried to change it to the admin lib and still getting the same behaviour. Maybe it's a `deno` thing?

**Comment by uriva** [comment]
It's a deno thing, I'm using a deno.json file to let it know what `@instantdb/react` means, but since the file is in a cousin directory deno does not like it.

I can't seem to find a good way to reuse code between the client and server.

**Comment by stopachka** [comment]
Hey @uriva , one idea for sharing code: 

What if you also added `@instantdb/core` to your dependencies? 

`@instantdb/core` also has `i` and all the utility types, which are used in both admin and react too. Perhaps you can use that as the base?

**Comment by uriva** [comment]
@stopachka I don't think the issue is with depending on react, I think it's because deno doesn't apply the module import resolution on files outside the directory path. I will try with a deno react client side as well.
