### ISSUE TITLE
example of `instant.perms.ts`?

### ISSUE THREAD

**Issue by sbdchd** [instantdb/instant#7]
In https://www.instantdb.com/docs/permissions#permissions-as-code the docs mention `instant.perms.ts` being supported, is there an example hanging around somewhere?

**Comment by arn314** [comment]
I found an example here: https://github.com/jsventures/instldraw?tab=readme-ov-file#%EF%B8%8F-permissions

**Comment by nezaj** [comment]
Closing this issue but feel free to re-open if you feel like this isn't enough guidance!

**Comment by sbdchd** [comment]
Yeah the linked file is json, is there not a typescript one?

**Comment by nezaj** [comment]
@stopachka We generate one right now when someone does `instant-cli init` -- I wonder though if it would be helpful to surface that some way?

**Comment by nezaj** [comment]
This is now in the docs! https://www.instantdb.com/docs/cli#push-schema
