### ISSUE TITLE
SDK for VueJS

### ISSUE THREAD

**Issue by nimonian** [instantdb/instant#99]
I'd be interested in a VueJS SDK. I'd also be interested in contributing to it.

I did some initial tinkering with the React SDK to see how it would translate to Vue. There are maybe a few discussions to be had around balancing idiomatic Vue (e.g. useQuery as a composable?) against keeping a similar API to Instant's other SDK's.

If a repo discussions tab opens up I will start a thread there :+1:

**Comment by nimonian** [comment]
https://github.com/instantdb/instant/pull/160#issuecomment-2334974953

**Comment by wobsoriano** [comment]
> I was tinkering with the sdk as well and made a [version for vuejs](https://github.com/Dorilama/instantdb-vue) with all the features of the react sdk. I would love some feedback/discussions about it :)

Looks great!
